[package]
name = "fsindex-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features=["serde"] }
eframe = { version = "0.24", features=["glow"] }
fsindex-core = { path = "../core" }
rfd = "0.14"
