[package]
name = "fsindex-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features=["serde"] }
clap = { version = "4.5", features = ["derive"] }
comfy-table = "7"
fsindex-core = { path = "../core" }
